### ISSUE TITLE
Error after run lando start

### ISSUE THREAD

**Issue by kamalkech** [ro0NL/symfony-lando#2]
lando version : `v3.0.0-rc.1`

lando start

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
ERROR: Invalid interpolation format for "environment" option in service "appserver": "^https?://localhost(:[0-9]+)?$"
error: Failed after 5 retries with backoff 500 and error Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at dc (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at compose (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at exports.start.datum (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
```

**Comment by ro0NL** [comment]
Hi @kamalkech 

i recently updated to RC2 (now RC7) and updated this repo as such. So to avoid any compatibility issues i strongly suggest to update.

I think the error is related to an invalid var in your .env file, which is automatically loaded by docker/lando pre RC2. Hence you should update, see https://docs.devwithlando.io/guides/updating-to-rc2.html#environment-files

As we're not configuring `env_file: .env` it makes sure everything is loaded by Symfony Dotenv. Loading envs with docker might lead to issues: https://github.com/symfony/recipes/pull/487 (i think CORS_ALLOW_ORIGIN actually bugs you, isnt it?)

**Comment by kamalkech** [comment]
@ro0NL but not found any solution to fixe that :(

**Comment by ro0NL** [comment]
me neither :) i decided to leave handling of _application_ env vars (defined in .env) up to Symfony Dotenv. 

By updating lando to RC2 or above, the default .env is not loaded by Docker anymore (which only allows a subset of env var syntax), as such we fallback to Dotenv.

**Comment by ro0NL** [comment]
@kamalkech  All good then?
